name: iris_ai_final
description: Project Iris A.I. - Final Full Offline + Online Smart Assistant

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_ml_kit: ^0.15.0
  flutter_tts: ^4.0.2
  speech_to_text: ^6.3.0
  camera: ^0.10.5+2
  path_provider: ^2.1.3
  shared_preferences: ^2.2.2
  local_auth: ^2.1.7
  animated_text_kit: ^4.2.2
  avatar_glow: ^2.0.2
  flutter_spinkit: ^5.2.0
  flutter_local_notifications: ^16.3.2
  permission_handler: ^11.3.0
  flutter_svg: ^2.0.9
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/sounds/
