name: iris_ai_beta
description: Smart modular AI assistant built in Flutter.
version: 0.9.1+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^6.5.1
  flutter_tts: ^4.0.2
  google_fonts: ^6.1.0
  avatar_glow: ^2.0.2
  permission_handler: ^11.3.0
  local_auth: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/audio/
